# Generated by Django 4.2.4 on 2023-11-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_remove_category_parent_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Цена')),
                ('old_price', models.IntegerField(default=0, verbose_name='Старая цена')),
                ('discount', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('KGZ', 'KGZ'), ('RUB', 'RUB'), ('EURO', 'EURO'), ('USD', 'USD')], default='KGZ', max_length=255, null=True, verbose_name='Валюта')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product', to='categories.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Скидка')),
                ('has_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
