# Generated by Django 4.2.4 on 2023-11-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(choices=[('В наличии', 'В наличии'), ('На складе', 'На складе'), ('Нет в наличии', 'Нет в наличии')], default='В наличии', verbose_name='Наличие товара'),
        ),
    ]
