# Generated by Django 4.2.4 on 2023-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('На складе', 'На складе'), ('Нет в наличии', 'Нет в наличии')], default='В наличии', max_length=20, verbose_name='Наличие товара'),
        ),
    ]
