# Generated by Django 4.2.4 on 2023-11-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_parent_remove_category_slug_and_more'),
        ('product', '0005_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_product', to='categories.subcategory', verbose_name='Подкатегории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Старая цена'),
        ),
    ]
