# Generated by Django 4.2.4 on 2023-11-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_postcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_parent', to='categories.category', verbose_name='Подкатегории'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=12, verbose_name='Slug категории'),
            preserve_default=False,
        ),
    ]
