# Generated by Django 4.2.4 on 2023-11-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='image',
            new_name='img',
        ),
    ]
